### ISSUE TITLE
update `.gitignore` file

### ISSUE THREAD

**Issue by tanryberdi** [samjtro/go-algotrader#4]
We need to update `.gitignore` file for ignore all extension like `.idea/` and etc...

**Comment by samjtro** [comment]
Merged via commit: 4576c3eeb629f41a25292c1ab7218d0551e48ff0

Thanks for the help! I had been putting that off, so I appreciate you stepping up to get that done. Let me know if you need anything for getting off the ground with [go-tda](https://github.com/samjtro/go-tda). 

Cheers!

**Comment by tanryberdi** [comment]
> 

I will investigate this repos, i will let you know if i have any questions
